# 300
services:
  # promtail:
  #   image: grafana/promtail:latest
  #   volumes:
  #     - ../test0:/test0 
  #     - ../test1:/test1
  #     - ../test2:/test2
  #     - ./promtail-config.yml:/etc/promtail/config.yml
  #   command: -config.file=/etc/promtail/config.yml
  #   restart: unless-stopped
  
  # loki:
  #   image: grafana/loki:2.8.0
  #   ports:
  #     - '3100:3100'
    
  prometheus:
    image: prom/prometheus:latest 
    container_name: prometheus 
    ports:
      - "9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    network_mode: "host"   

  grafana:
    image: grafana/grafana:latest
    ports:
      - '3200:3000'
    volumes:
      - ./grafana:/var/lib/grafana  # 볼륨 마운트 추가
    depends_on:
      - prometheus
    
