global:
  scrape_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ["localhost:9090"]
  - job_name: raftchat
    static_configs:
      - targets: ["localhost:3000", "localhost:3001", "localhost:3002"]
